// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmAppCobVHtnRsAAvhDkJKscAKNfYyBRk',
    appId: '1:773030749299:web:41d88edd7a8cf79cc53606',
    messagingSenderId: '773030749299',
    projectId: 'project-74411',
    authDomain: 'project-74411.firebaseapp.com',
    databaseURL: 'https://project-74411-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-74411.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyEdWRNf4i0uOYCeN1AR2DVCZi65BzMgg',
    appId: '1:773030749299:android:dcb44405953fe96ec53606',
    messagingSenderId: '773030749299',
    projectId: 'project-74411',
    databaseURL: 'https://project-74411-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-74411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-yNizbZNnZYmooZMyR-qlB68kWaIV9A',
    appId: '1:773030749299:ios:dd7789848c798aa1c53606',
    messagingSenderId: '773030749299',
    projectId: 'project-74411',
    databaseURL: 'https://project-74411-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-74411.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
